version: '3.8'

services:
  trainer:
    build:
      dockerfile: Dockerfile.trainer
    volumes:
      - modelos_cnn_data:/app/modelos_cnn
    ports:
      - "8001:8001"
    # Puedes agregar otras configuraciones como variables de entorno, etc.
    # environment:
    #   - ...

  frontend:
    build:
      dockerfile: Dockerfile.front
    ports:
      - "8501:8501"
      - "8002:8002"
    volumes:
      - modelos_cnn_data:/app/modelos_cnn
    # Puedes agregar otras configuraciones como variables de entorno, etc.





volumes:
  modelos_cnn_data:

  