apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-trainer-data-base
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-trainer-data-base
  template:
    metadata:
      labels:
        app: model-trainer-data-base
    spec:
      containers:
      - name: model-trainer-data-base
        image: omargo33/trainer-final:1.0.7
        ports:
          - containerPort: 8001
        volumeMounts:
        - name: model-volume
          mountPath: /app/modelos_cnn
      volumes:
      - name: model-volume
        persistentVolumeClaim:
          claimName: model-pvc
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: model-trainer-data-base-service
spec:
  type: NodePort
  selector:
    app: model-trainer-data-base
  ports:
    - port: 8001
      targetPort: 8001
      nodePort: 30001