_wandb:
    value:
        cli_version: 0.26.1
        e:
            8k2cywctxjhdu13cj81h70qjij0zpeb1:
                codePath: modelo/train.py
                codePathLocal: train.py
                cpu_count: 12
                cpu_count_logical: 16
                disk:
                    /:
                        total: "1005867986944"
                        used: "456412565504"
                email: omar.velez@yachaytech.edu.ec
                executable: /home/ovelez/Documentos/cursos/Maestria/Produccion/finalModulo/modelo/.venv/bin/python3
                git:
                    commit: 8a194239b2c1f8225c951686f0c11486caed795e
                    remote: https://github.com/omargo33/finalModulo.git
                host: ovelez-NUC12WSHi7
                memory:
                    total: "33143771136"
                os: Linux-6.8.0-110-generic-x86_64-with-glibc2.39
                program: /home/ovelez/Documentos/cursos/Maestria/Produccion/finalModulo/modelo/train.py
                python: CPython 3.12.3
                root: /home/ovelez/Documentos/cursos/Maestria/Produccion/finalModulo/modelo
                startedAt: "2026-04-25T05:12:21.809354Z"
                writerId: 8k2cywctxjhdu13cj81h70qjij0zpeb1
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
            "2":
                - 2
                - 3
                - 5
                - 53
            "3":
                - 3
                - 8
                - 16
            "4": 3.12.3
            "5": 0.26.1
            "10":
                - 9
                - 17
            "12": 0.26.1
            "13": linux-x86_64
batch_size:
    value: 32
epochs:
    value: 100
