CREATE TABLE CABECERA_PRESTAMOS (
	NUMERO_CREDITO NUMERIC(10,0) NOT NULL,
	CODIGO_EMPRESA NUMERIC(4,0) NOT NULL,
	CODIGO_ACT_FINANCIERA NUMERIC(2,0) NOT NULL,
	CODIGO_TIPO_CLI NUMERIC(4,0) NOT NULL,
	CODIGO_MONEDA NUMERIC(2,0) NOT NULL,
	CODIGO_PRODUCTO NUMERIC(4,0) NOT NULL,
	CODIGO_SOCIO NUMERIC(13,0) NOT NULL,
	FECHA_CREDITO DATE NOT NULL,
	CODIGO_PERIOC VARCHAR(6) NOT NULL,
	CODIGO_ORIREC VARCHAR(2) NOT NULL,
	DEB_AUT VARCHAR(1) NOT NULL,
	CANT_SOLI NUMERIC(16,2) NOT NULL,
	TOT_INNVERSION NUMERIC(16,2),
	BASE_CREDITO NUMERIC(16,2) NOT NULL,
	NUM_CUOTAS NUMERIC(6,0) NOT NULL,
	TASA_INTERES NUMERIC(6,2) NOT NULL,
	MORA NUMERIC(6,2) NOT NULL,
	TAB_AMORTIZA VARCHAR(1) NOT NULL,
	TOT_DIAS_MORA NUMERIC(8,2) NOT NULL,
	TOT_NUM_MORAS NUMERIC(6,2) NOT NULL,
	ESTADO_CRED VARCHAR(1) NOT NULL,
	ESTADO VARCHAR(1) NOT NULL,
	PER_GRACIA NUMERIC(6,2) NOT NULL,
	CAPITAL_PORPAG NUMERIC(16,2) NOT NULL,
	MISMODIA VARCHAR(1) NOT NULL,
	NUMDIAS NUMERIC(6,0) NOT NULL,
	OFICRE NUMERIC(6,0),
	OBS VARCHAR(300),
	CODIGO_SUCURSAL NUMERIC(4,0) NOT NULL,
	CODIGO_AGENCIA NUMERIC(4,0) NOT NULL,
	PIGPER VARCHAR(1) NOT NULL,
	INTERES_FIJO VARCHAR(1),
	PORC_PIG NUMERIC(16,2),
	FECINI DATE,
	FECFIN DATE,
	JUDICIAL VARCHAR(1) DEFAULT 'N',
	CODIGO_GRUPO NUMERIC(3,0) NOT NULL,
	CODIGO NUMERIC(6,0),
	CODIGO_DESTINO NUMERIC(2,0),
	CODIGO_DESTINO_DET NUMERIC(3,0),
	COSTO_JUDICIAL NUMERIC(16,2) DEFAULT 0,
	NOTIFICACIONES NUMERIC(16,2) DEFAULT 0,
	GESTION_COBRO NUMERIC(16,2) DEFAULT 0,
	FECHA_GESTION_COBRO DATE,
	DESEM_PARC VARCHAR(1),
	MONTO_REAL NUMERIC(16,2) NOT NULL,
	SALDO_CAPITAL NUMERIC(16,2),
	CODIGO_USUARIO NUMERIC(5,0) NOT NULL,
	MONTO_ACREDITADO NUMERIC(16,2) NOT NULL,
	OBS_DESCRE VARCHAR(100),
	CODIGO_OCUPACION NUMERIC(3,0),
	VFLAT NUMERIC(10,2),
	METCRE VARCHAR(2),
	CENRIE VARCHAR(300),
	DESTINO_CREDITO VARCHAR(2),
	ACT_ECONOMICA_NVL1 VARCHAR(4),
	ACT_ECONOMICA_NVL2 VARCHAR(4),
	ACT_ECONOMICA_NVL3 VARCHAR(4),
	VALOR_A_APORTAR_CERTIFICADOS NUMERIC(13,2),
	VALOR_APORTADO_CERTIFICADOS NUMERIC(13,2),
	CODIGO_PAIS NUMERIC(4,0),
	CODIGO_PROVINCIA NUMERIC(4,0),
	CODIGO_CIUDAD NUMERIC(4,0),
	CODIGO_PARROQUIA NUMERIC(4,0),
	CODIGO_RIESGO VARCHAR(20),
	CODIGO_ACTIVIDAD_ECONOMICA NUMERIC(10,0) NOT NULL,
	
	CONSTRAINT PK_CABPRE PRIMARY KEY (NUMERO_CREDITO, CODIGO_EMPRESA)
);

CREATE INDEX CABECERA_PRESTAMOS_IDXESTADO ON CABECERA_PRESTAMOS (ESTADO_CRED);
CREATE INDEX FIS_CABECERA_PRESTAMOS_IDX1 ON CABECERA_PRESTAMOS (CODIGO_SOCIO);
CREATE INDEX GRUPO_RIESGO_IDX ON CABECERA_PRESTAMOS (CODIGO_GRUPO, CODIGO_RIESGO);
CREATE INDEX GRUPO_RIESGO_SUCURSAL_IDX ON CABECERA_PRESTAMOS (NUMERO_CREDITO, CODIGO_SUCURSAL, CODIGO_GRUPO, CODIGO_RIESGO, CODIGO_EMPRESA, ESTADO_CRED);
CREATE INDEX IND_FK_CP_PRO ON CABECERA_PRESTAMOS (CODIGO_PRODUCTO, CODIGO_ACT_FINANCIERA, CODIGO_MONEDA, CODIGO_EMPRESA);
CREATE INDEX INF_CBPREF ON CABECERA_PRESTAMOS (FECHA_CREDITO);
CREATE INDEX IX01_CABECERA_PRESTAMOS ON CABECERA_PRESTAMOS (NUMERO_CREDITO);
CREATE INDEX PK_CABCRESOC ON CABECERA_PRESTAMOS (CODIGO_SOCIO, CODIGO_EMPRESA);


CREATE TABLE AMORTIZACAL_PRESTAMOS (
	NUMERO_CREDITO NUMERIC(10,0) NOT NULL,
	CODIGO_EMPRESA NUMERIC(4,0) NOT NULL,
	ORDENCAL NUMERIC(4,0) NOT NULL,
	FECINICAL DATE NOT NULL,
	FECFINCAL DATE NOT NULL,
	SALDOCAL NUMERIC(16,2) NOT NULL,
	CAPITALCAL NUMERIC(16,2) NOT NULL,
	INTERESCAL NUMERIC(16,8) NOT NULL,
	DIASINTCAL NUMERIC(6,0) NOT NULL,
	FECHAINTCAL DATE,
	MORACAL NUMERIC(16,8) NOT NULL,
	DIASMORACAL NUMERIC(6,0) NOT NULL,
	FECHAMORACAL DATE,
	RUBROSCAL NUMERIC(16,8) NOT NULL,
	TOTALCAL NUMERIC(16,8) NOT NULL,
	ESTADOCAL VARCHAR(1) NOT NULL,
	ESTADO VARCHAR(1),
	CONSTRAINT CK_ACALPRESTAMOS_CAPITALCAL CHECK (COALESCE(CAPITALCAL, 0) >= 0)
);

CREATE INDEX IDX_AMORTIZACAL_PRESTAMOS ON AMORTIZACAL_PRESTAMOS (FECINICAL, ESTADOCAL);
CREATE INDEX IDX_AMORTIZACALPRE ON AMORTIZACAL_PRESTAMOS(NUMERO_CREDITO, ORDENCAL, CODIGO_EMPRESA);

